# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

# c_compiler:
#   - vs2022                     # [win]
# cxx_compiler:
#   - vs2022                     # [win]
