{% set name = "gsplat" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gsplat-{{ version }}.tar.gz
    sha256: 3a9a69f5b4e82c8e31a609e7a32ab41340f72e8ebea37014f3b9f46d31df0817
    patches:
      - patches/0001-Remove-ninja-from-install-requirements.patch
  - url: https://github.com/g-truc/glm/archive/33b4a621a697a305bc3a7610d290677b96beb181.tar.gz
    sha256: fa761b941987933884b0d21d5b86930789061f026ba163d47cebbc5b00be277b
    folder: gsplat/cuda/csrc/third_party/glm

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [cuda_compiler_version == "11.8"]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - {{ stdlib("c") }}
    - cmake
    - cuda-nvcc
    - cuda-toolkit
    - ninja
    - pip         # [target_platform != build_platform]
    - pybind11    # [target_platform != build_platform]
    - python      # [target_platform != build_platform]
    - pytorch     # [target_platform != build_platform]
    - setuptools  # [target_platform != build_platform]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - cuda-nvcc
    - cuda-toolkit
    - jaxtyping
    - rich >=12
    - pip
    - python
    - pytorch
    - setuptools
  run:
    - cuda-cudart
    - jaxtyping
    - numpy
    - python
    - pytorch
    - rich >=12
    - typing_extensions

test:
  imports:
    - gsplat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nerfstudio-project/gsplat
  summary: CUDA accelerated rasterization of gaussian splatting
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
