schema_version: 1

context:
  name: gsplat
  version: "1.5.3"
  build_number: 5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: |
      https://github.com/nerfstudio-project/${{ name }}/archive/v${{ version }}.tar.gz
    sha256: 8a24428b8ea2ce7c3e10fcf5aa20e20fe503b8329c96db797f4eab703729aac3
    patches:
      - patches/0001-Remove-ninja-from-install-requirements.patch

  - url: https://github.com/g-truc/glm/archive/33b4a621a697a305bc3a7610d290677b96beb181.tar.gz
    sha256: fa761b941987933884b0d21d5b86930789061f026ba163d47cebbc5b00be277b
    target_directory: gsplat/cuda/csrc/third_party/glm

build:
  number: ${{ build_number }}
  script:
    - export MAX_JOBS=1
    - export TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6;8.9;9.0"
    - export CUDA_HOME="$PREFIX"
    - $PYTHON -m pip install . -vv --no-build-isolation --no-deps
  skip:
    - cuda_compiler_version == "None"
    - osx
    - win

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cmake
    - cuda-nvcc
    - ninja
    - if: target_platform != build_platform
      then:
        - pip
        - pybind11
        - python
        - pytorch
        - setuptools
  host:
    - cuda-version ${{ cuda_compiler_version }}.*
    - cuda-nvcc
    - cuda-cudart-dev
    - jaxtyping
    - rich >=12
    - pip
    - python
    - pytorch
    - setuptools
  run:
    - jaxtyping
    - numpy
    - python
    - pytorch
    - rich >=12
    - typing_extensions

tests:
  - python:
      imports:
        - gsplat
      pip_check: true

about:
  summary: CUDA accelerated rasterization of gaussian splatting
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/nerfstudio-project/gsplat

extra:
  recipe-maintainers:
    - jeongseok-meta
